Resources:
  # We are describing a DynamoDB table resource called NotesTable.
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # The table we get from a custom variable. will be generated in Serverless.yml
      TableName: ${self:custom.tableName}
      # We are also configuring the two attributes of our table as userId and noteId.
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
